name: ENV Variables
on: push
env:
  WF_ENV: Available to all jobs


jobs:
  log-env-variables:
    runs-on: ubuntu-20.04
    env:
      JOB_ENV: Available to all the steps from this jobs
    steps:
      - name: Log Env Varibales
        env:
          STEPS_ENV: Available only to this step
        run: |
          echo "WF_ENV : ${WF_ENV}"
          echo "JOB_ENV : ${JOB_ENV}"
          echo "STEP_ENV : ${STEP_ENV}"
      - name: Another Log Env Variables
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
